#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nginx-rtmp-module
Version  : 1.2.1
Release  : 3
URL      : https://github.com/arut/nginx-rtmp-module/archive/v1.2.1.tar.gz
Source0  : https://github.com/arut/nginx-rtmp-module/archive/v1.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nginx-rtmp-module-lib = %{version}-%{release}
BuildRequires : buildreq-nginx
BuildRequires : openssl-dev

%description
# NGINX-based Media Streaming Server
## nginx-rtmp-module
### Project blog
http://nginx-rtmp.blogspot.com

%package lib
Summary: lib components for the nginx-rtmp-module package.
Group: Libraries

%description lib
lib components for the nginx-rtmp-module package.


%prep
%setup -q -n nginx-rtmp-module-1.2.1
cd %{_builddir}/nginx-rtmp-module-1.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
nginx-module configure
nginx-module build

%install
nginx-module install %{buildroot}


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/nginx-mainline/ngx_rtmp_module.so
